### ISSUE TITLE
BE User missing

### ISSUE THREAD

**Issue by Ernestopheles** [isotope/demo#2]
After installation into a fresh Contao 4.13.30 according to the manuals the demo is working, but there are no BE Users except the one I added during the installation process of Contao.

DB and BE both only show this one User I added.

**Comment by netzarbeiter** [comment]
If you have done the installation as described [here](https://www.isotopeecommerce.org/en/demo.html
), then the user will be imported in step 5 with the [isotope-demo/isotope-demo-data.sql](https://github.com/isotope/demo/blob/master/skeleton/templates/isotope-demo/isotope-demo-data.sql).

**Comment by Ernestopheles** [comment]
Sorry, you are quite quick completing this!

1. I found 2 points in the installation process that might mislead the user:
2. I got an extra message in the install tool after Step 5 finished.

For both see screenshots and explanations in the forum:

https://community.contao.org/de/showthread.php?85784-IsotopeDemo-fehlende-BE-User&p=576522#post576522

**Comment by netzarbeiter** [comment]
After I was able to install the demo with the guide without any probleme, I closed this ticket.

1. When we created the demo, the possibility of updating the database via the manager did not exist yet. But if you follow the way written in the instructions, it still works fine.

2. This extra message comes from the ChangeLanguage extension and only says that the migration of the database schema was successful.

**Comment by Ernestopheles** [comment]
Thanks for explaining.

After all I recommend to make the guide more clearly regarding the 2 points and maybe the ChangLanguage thing could be mentioned in the guide as well.

And I do not quite understand why a database update done from 2 different points but at the same step in the process lead to different (and  one time falsy) results.
