### ISSUE TITLE
Error add package on CM

### ISSUE THREAD

**Issue by raffaelloit** [isotope/demo#4]
Contao 4.13.34; PHP 8.1, Contao Manager 1.8.0 - Clean install on a subdomain.
When I upload the zip file (isotope-demo-main.zip) at the CM Packages Manager I get following error message:

`Die composer.json Schema-Validierung ist fehlgeschlagen. Error validating /version: The property version is required`

Which composer.json is meant by this? The one from Contao or the file contained in the ZIP file? I can't find any errors in the various logs (Contao, CM).

**Comment by aschempp** [comment]
Leider ist die Doku (https://www.isotopeecommerce.org/en/demo.html) veraltet. Wenn du ein neues Contao installierst, kannst du statt der regulären Installation ein Theme wählen, und dann mit der Suchfunktion direkt die Isotope Demo installieren.

**Comment by netzarbeiter** [comment]
Ich werde die Doku in den nächsten Tagen anpassen.

**Comment by netzarbeiter** [comment]
Die [Doku](https://www.isotopeecommerce.org/de/demo.html) ist jetzt nicht mehr veraltet. Viel Spass!
